<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Why can LASSO shrink to exactly 0, but Ridge can’t? A calculus POV</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="penalties_files/libs/clipboard/clipboard.min.js"></script>
<script src="penalties_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="penalties_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="penalties_files/libs/quarto-html/popper.min.js"></script>
<script src="penalties_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="penalties_files/libs/quarto-html/anchor.min.js"></script>
<link href="penalties_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="penalties_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="penalties_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="penalties_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="penalties_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why can LASSO shrink to exactly 0, but Ridge can’t? A calculus POV</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><br> <img src="ceo.png" style="float: right; margin-left: 15px; margin-bottom: 10px;" width="200"> You’re a top statistician (or data scientist, whichever sounds fanciest to your ear) who’s just been hired on a consulting mission for an established company. You’re seated with the CEO, and they’re telling you they want to overhaul the firm’s workforce. They’ve compiled some data on employee performance and from the firm’s financial reports for you, and they’re pretty confident that a subset of their employees does the majority of the work while the others are mostly busy scrolling on Tiktok pretending to work. They also believe the quantity of energy drink that an employee downs every day is linearly associated with revenue and a highly accurate indicator of employee productivity…</p>
<p>So they basically want you to perform “employee selection” by modelling the daily company revenue with their energy drink intake. A plethora of questions starts rushing to your head</p>
<blockquote class="blockquote">
<p><em>“maybe I should use the Lasso since it can shrink the coefficients of some employees to zero… but how does it do that, by the way? Also, should I prioritise finding the set of employees that best predicts the company revenue, or the smallest decently predictive one that will get the most employees fired thereby saving the firm money?”</em></p>
</blockquote>
<p>; the consequences are not yours to bear anyway. You’re just here to give advice.</p>
<center>
<img src="lasso-ridge.png" alt="drawing" width="700">
</center>
<p>The image above comes from <em>Elements of Statistical Learning</em> (<em>ESL</em>) by Hastie, Tibshirani and Friedman. It’s a very nice visualisation (also perfectly correct mathematically, not taking that away) which gives you the gist of Lasso (left in image) vs Ridge (right in image) and why one can zero out slope coefficients and the other not. However if you want an actual mental image of the math behind it that gave birth to this result, you’d need to prove that the smallest red contour of the cost function to intersect with the boundary of the Lasso penalty region defined by <span class="math inline">\(|\beta_1|+|\beta_2|\leq t\)</span> does so at a corner, which is not immediately straightforward to me at least (I haven’t even tried past what I’ve just written though…).</p>
<p>The good news is we can also easily show the exact same thing with a bit of high-school level calculus and algebra, in a form that’s more familiar to me as a statistics grad and to some of the readers surely. Depending which branch of math you’re most proficient at, you might benefit from knowing the geometric proof over the calculus one. But I find the simplicity and intuitive aspect| of the calculus route hard to beat. And, if you’re gonna do some more advanced work on various penalties down the line, it’s probably useful to have a clear mental picture of the inner workings of the L1 and L2 penalties in calculus language.</p>
<p>In <em>ESL</em>, Hastie et al.&nbsp;spend a large part of the sections on penalised regression describing their Bayesian and geometric interpretations, and only give the algebraic expression of the Ridge coefficients without dwelling on the shape of the Lasso objective and how it helps understand the shrinkage to the exact <span class="math inline">\(0\)</span>. So, that’s what we’re going to be doing in this article.</p>
<section id="enough-with-the-yapping" class="level3">
<h3 class="anchored" data-anchor-id="enough-with-the-yapping">Enough with the yapping</h3>
<p>For simplicity, throughout this entire post we’ll work with a stupidly simple affine function <span class="math inline">\(f\)</span> that strives to model an outcome <span class="math inline">\(y\)</span> with a single feature <span class="math inline">\(x\)</span>: <span class="math display">\[
f(x) = \beta_0 + \beta_1x
\]</span></p>
<p>Our dataset contains <span class="math inline">\(n\)</span> observations.</p>
</section>
<section id="prelude-ols" class="level2">
<h2 class="anchored" data-anchor-id="prelude-ols">Prelude: OLS</h2>
<p>In the case of ordinary least squares regression, in order to find the coefficients that give the best fit on our data, we minimise the mean squared residual: <span class="math display">\[\begin{align*}
\min_{\beta_0,\beta_1}\frac1n\sum_{i=1}^n{(y_i-\beta_0-\beta_1x_i)^2}
\end{align*}\]</span></p>
<p>or equivalently</p>
<p><span class="math display">\[\begin{align*}
\min_{\beta_0,\beta_1}J(\beta_0, \beta_1)
\end{align*}\]</span></p>
<p>where <span class="math inline">\(J\)</span> is the cost function, here the mean squared error in the OLS case, but we will stick to “cost” henceforth. Our goal is to find the parameter values where <span class="math inline">\(J\)</span> is minimised: <span class="math display">\[\begin{align*}
\hat{\beta}_0, \hat{\beta}_1 &amp; = \arg\min_{\beta_0, \beta_1} J(\beta_0, \beta_1)
\end{align*}\]</span></p>
<p>Since <span class="math inline">\(J\)</span> is strictly convex we can safely say that if it has one critical point then that point is its global minimum, so we can find <span class="math inline">\((\hat{\beta}_0, \hat{\beta}_1)\)</span> by solving the following system: <span class="math display">\[
\left\{ \begin{aligned}
  \frac{\partial J}{\partial \beta_0} = 0 \\
  \frac{\partial J}{\partial \beta_1} = 0
\end{aligned} \right.
\]</span></p>
<p>Nothing new here. Since OLS is not the focus today, we’ll skip the details and move on to the next part right away, but just remember that the system above yields: <span class="math display">\[
\hat\beta_0 = \bar y - \hat\beta_1 \bar x
\]</span></p>
<p>where the bar denotes the mean of the given variable in the dataset. For any <span class="math inline">\(\hat\beta_1\)</span>, this is the value of <span class="math inline">\(\beta_0\)</span> when the partial derivative of <span class="math inline">\(J\)</span> wrt. <span class="math inline">\(\beta_0\)</span> is <span class="math inline">\(0\)</span>, or in other words the optimal <span class="math inline">\(\beta_0\)</span> for any given <span class="math inline">\(\hat\beta_1\)</span>.</p>
<section id="interlude-why-penalise-at-all" class="level3">
<h3 class="anchored" data-anchor-id="interlude-why-penalise-at-all">Interlude: why penalise at all</h3>
<p>A penalised regression model adds a regularisation term (or penalty) to the cost function to encourage the shrinkage of coefficients so that their standard error is reduced, which is especially useful when your dataset has high collinearity. I’ll directly quote Hastie &amp; Tibshirani from the <em>ESL</em> book again, as I probably can’t put it better than they do:</p>
<blockquote class="blockquote">
<p><em>When there are many correlated variables in a linear regression model,</em> <em>their coefficients can become poorly determined and exhibit high variance.</em> <em>A wildly large positive coefficient on one variable can be canceled by a</em> <em>similarly large negative coefficient on its correlated cousin. By imposing a</em> <em>size constraint on the coefficients, […] this problem is alleviated.</em></p>
</blockquote>
</section>
</section>
<section id="ridge" class="level2">
<h2 class="anchored" data-anchor-id="ridge">Ridge</h2>
<p>Now let’s move on to Ridge regression, which is a type of penalised linear regression. Ridge adds what we call the “L2 penalty” to the cost:</p>
<p><span class="math display">\[\begin{align*}
J(\beta_0, \beta_1) &amp; = \frac1n\sum_{i=1}^n{(y_i-\beta_0-\beta_1x_i)^2} + \lambda\beta_1^2
\end{align*}\]</span></p>
<p>The name of this penalty comes from the fact that it is the squared L2 norm of the coefficient vector, which we multiply by <span class="math inline">\(\lambda\)</span> to adjust the strength of the regularisation. Since our model here has just one feature, the L2 norm is just the squared slope coefficient. <span class="math inline">\(J\)</span> being a sum of parabola in <span class="math inline">\(\beta_1\)</span>, the shape of the Ridge objective is also a parabola, though not continuous at <span class="math inline">\(\beta_1=0\)</span> (unless the dataset fulfills some conditions which you’ll see below, in which case <span class="math inline">\(\beta_1\)</span> would always be <span class="math inline">\(0\)</span> for all <span class="math inline">\(\lambda\)</span> anyway).</p>
<p>In order to minimise <span class="math inline">\(J\)</span>, we solve the same system as for OLS. Since the L2 penalty does not depend on <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\hat\beta_0\)</span> has the same expression as for OLS, so we use the result from the OLS section to substitute <span class="math inline">\(\hat\beta_0\)</span> with its expression in the following. Thus, we’re just left with solving (the hats were omitted for notational simplicity):</p>
<p><span class="math display">\[
\begin{align*}
&amp; \frac{\partial J}{\partial \beta_1} = \frac{\partial}{\partial \beta_1} \left( \frac1n\sum_{i=1}^n{(y_i-\beta_0-\beta_1x_i)^2} + \lambda\beta_1^2 \right) = 0 \\
&amp; \Rightarrow \frac1n\sum_{i}{-2x_i(y_i-\beta_0-\beta_1x_i)} + 2\lambda \beta_1 = 0 \tag*{\small we can divide all by 2}\\
&amp; \Leftrightarrow \frac1n\left( \beta_1n\overline{x^2} + \sum_i{x_i(\beta_0-y_i}) \right) + \lambda \beta_1 = 0 \tag*{\small where $\overline{x^2} = \frac1n\sum_i{x_i^2}$} \\
&amp; \Leftrightarrow \beta_1\overline{x^2} + \bar x\bar y - \beta_1\bar x^2 - \overline{xy} + \lambda\beta_1 = 0 \; \tag*{\small where $\overline{xy} = \frac1n\sum_i{x_iy_i}$} \\
&amp; \Leftrightarrow \beta_1(\overline{x^2} + \lambda - \bar x^2) = \overline{xy} - \bar x\bar y
\end{align*}
\]</span></p>
<p>and by isolating <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math display">\[
\begin{align*}
\hat\beta_1 &amp; = \frac{\overline{xy} - \bar x\bar y}{\overline{x^2} - \bar x^2 + \lambda}
\end{align*}
\]</span></p>
<p>Now, for the sake of mathematical rigour, we’ll consider the dataset fixed, <span class="math inline">\(\boldsymbol{x}\)</span> and <span class="math inline">\(\boldsymbol{y}\)</span> are not both <span class="math inline">\(\boldsymbol{0}\)</span>, and both don’t have infinite values. Then if we make <span class="math inline">\(\lambda\)</span> very large the denominator will also become very large, and <span class="math inline">\(\hat\beta_1\)</span> very small:</p>
<p><span class="math display">\[
\lim_{\lambda \to +\infty}\hat\beta_1 = 0
\]</span></p>
<p>However that limit can never be reached for a finite <span class="math inline">\(\lambda\)</span>: that is why in real applications Ridge can shrink coefficients, but never zero them out.</p>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>the slope coefficient is inversely proportional to the regularisation strength <span class="math inline">\(\lambda\)</span>, so as you increase the latter to very large values, the slope is shrunk toward 0. Since 0 is the limit of <span class="math inline">\(\hat\beta_1\)</span> which is only reached when <span class="math inline">\(\lambda\)</span> is infinite, Ridge never zeroes out coefficients in practice.</p>
</section>
</section>
<section id="lasso" class="level2">
<h2 class="anchored" data-anchor-id="lasso">LASSO</h2>
<p>Onto the Lasso, another type of penalised regression. The Lasso adds the L1 penalty to the mean squared error: instead of L2 norm, we’re now working with the L1 norm which is the sum of the absolute coefficients. Thankfully our model is very simple, so the L1 norm is just the absolute value of the slope here. Our cost function is now: <span class="math display">\[
\begin{align*}
J(\beta_0, \beta_1) &amp; = \frac1n \sum_{i=1}^n{(y_i-\beta_0-\beta_1x_i)^2} + \lambda|\beta_1|
\end{align*}
\]</span></p>
<p>and we’re solving the same optimisation problem as with Ridge earlier. Since <span class="math inline">\(J\)</span> is the sum of a parabola and absolute value, the objective is not smooth and looks like a straightened parabola axially asymmetric around the vertical line at its minimum.</p>
<p>The MSE part in <span class="math inline">\(\partial_{\beta_1} J\)</span> is the same, so we can take its expanded expression from the previous section and fix the penalty part while not forgetting to also divide it by 2 (which we’d already done for Ridge earlier):</p>
<p><span class="math display">\[\begin{align*}

\beta_1(\overline{x^2} - \bar x^2) + \bar x\bar y - \overline{xy} + \frac12\frac{\partial}{\partial \beta_1}(\lambda |\beta_1|) &amp; = 0 \\

\text{given} \frac{\partial}{\partial \beta_1}(|\beta_1|) = \frac{\beta_1}{|\beta_1|} = \text{sgn$(\beta_1)$,} \\

\Leftrightarrow \beta_1(\overline{x^2} - \bar x^2) + \bar x\bar y - \overline{xy} + \frac12 \text{sgn$(\beta_1)$}\lambda &amp; = 0
\end{align*}\]</span></p>
<p>and by isolating <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math display">\[
\hat\beta_1 = \frac{\overline{xy} - \bar x\bar y - \frac12 \text{sgn}(\beta_1) \lambda}{\overline{x^2} - \bar x^2} \;,\; \text{where sgn$(\beta_1)$} =
\left\{ \begin{aligned}
+ \;\; \text{if $\hat\beta_1 &gt; 0$} \\
- \;\; \text{if $\hat\beta_1 &lt; 0$}
\end{aligned} \right.
\]</span></p>
<p>Pay attention to the numerator of <span class="math inline">\(\hat\beta_1\)</span> and notice how if we crank up the regularisation strength such that <span class="math inline">\(\lambda \geq 2(\overline{xy} - \bar x\bar y)\)</span>, then we run into an issue, because the very assumptions under which <span class="math inline">\(\hat\beta_1\)</span> was defined above break in <em>both</em> cases of <span class="math inline">\(\text{sgn}\)</span> <span class="math inline">\((\beta_1)\)</span>; let <span class="math inline">\(\lambda_{lim}=2(\overline{xy} - \bar x\bar y)\)</span> and the <span class="math inline">\(\hat\beta_1\)</span> formula above yields</p>
<ul>
<li><span class="math inline">\(\hat\beta_1 \leq 0\)</span> in the case <span class="math inline">\(\hat\beta_1 &gt; 0\)</span>, since <span class="math inline">\(\lambda \geq \lambda_{lim}\)</span> makes the numerator 0 or negative,</li>
<li><span class="math inline">\(\hat\beta_1 \geq 0\)</span> in the case <span class="math inline">\(\hat\beta_1 &lt; 0\)</span>, since <span class="math inline">\(\lambda \geq \lambda_{lim}\)</span> makes the numerator 0 or positive.</li>
</ul>
<p>In other words <span class="math inline">\(\hat\beta_1\)</span> does not lie in the interval that the assumption about its sign said. Sounds confusing. This mess basically means that since those assumptions are violated when we increase <span class="math inline">\(\lambda\)</span> past <span class="math inline">\(\lambda_{lim}\)</span>, the minimum of <span class="math inline">\(J\)</span> is not reached when <span class="math inline">\(\hat\beta_1 &gt; 0\)</span> nor when <span class="math inline">\(\hat\beta_1 &lt; 0\)</span>.</p>
<p>What’s left? We know that since <span class="math inline">\(J\)</span> is strictly convex (the MSE is strictly convex, and the absolute value is convex), continuous in <span class="math inline">\(\beta_1\)</span> on <span class="math inline">\(\mathbb{R}\)</span> (it doesn’t have any breaks), and coercive <span class="math inline">\((\lim_{\beta_1 \to \pm \infty}J=+\infty)\)</span>, its global minimum is guaranteed to exist. So the only possibility we’re left with for that minimum is <span class="math inline">\(\hat\beta_1 = 0\)</span>, even though <span class="math inline">\(\partial_{\beta_1} J\)</span> is not defined at <span class="math inline">\(\hat\beta_1 = 0\)</span>. This is a nice example that illustrates why differentiability is not a necessary condition for a minimum !</p>
<section id="lets-visualise-the-lasso-shrinkage-in-action" class="level3">
<h3 class="anchored" data-anchor-id="lets-visualise-the-lasso-shrinkage-in-action">Let’s visualise the Lasso shrinkage in action!</h3>
<p>We’re going to generate a small mock dataset with 20 data points (<span class="math inline">\(x,y\)</span>). It doesn’t really matter which distribution <span class="math inline">\(x\)</span> comes from, and we’ll make it so <span class="math inline">\(y\)</span> is partly but not perfectly explained by <span class="math inline">\(x\)</span>.</p>
<p>Here’s a very ugly scatter plot to visualise the dependency between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>:</p>
<div id="d83f61ed" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>size <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">1</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.exponential(scale<span class="op">=</span><span class="dv">1</span>, size<span class="op">=</span>size)  <span class="co">#random idea of distro, dont ask me why</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> x <span class="op">+</span> np.random.normal(loc<span class="op">=</span><span class="dv">0</span>, scale<span class="op">=</span><span class="fl">0.3</span>, size<span class="op">=</span>size)  <span class="co">#we make y dependent on x, but add some small gaussian noise</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="penalties_files/figure-html/cell-2-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s generate a grid of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> values and compute the curve of the cost function:</p>
<div id="220ddd58" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> <span class="dv">1_000</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>, res)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="op">=</span> np.mean(y) <span class="op">-</span>np.mean(x)<span class="op">*</span>beta_1</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_cost(lambda_):</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [np.mean(np.square(y<span class="op">-</span>beta_0[i]<span class="op">-</span>beta_1[i]<span class="op">*</span>x)) <span class="op">+</span> lambda_<span class="op">*</span><span class="bu">abs</span>(beta_1[i]) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(res)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s start out with a small value, say <span class="math inline">\(\lambda=0.1\)</span>, and see what <span class="math inline">\(J\)</span> looks like:</p>
<div id="3b1e502d" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.ticker <span class="im">import</span> MultipleLocator</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cost <span class="op">=</span> compute_cost(lambda_<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>min_idx <span class="op">=</span> np.argmin(cost)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>beta_min <span class="op">=</span> beta_1[min_idx]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>cost_min <span class="op">=</span> cost[min_idx]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>zero_idx <span class="op">=</span> np.argmin(np.<span class="bu">abs</span>(beta_1 <span class="op">-</span> <span class="dv">0</span>))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>cost_zero <span class="op">=</span> cost[zero_idx]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">5</span>))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plt.plot(</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    beta_1,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    cost,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#721d98"</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Cost function"</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    cost_zero,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#ff6d00"</span>,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="vs">r"</span><span class="dv">$\b</span><span class="vs">eta_1 = 0</span><span class="dv">$</span><span class="vs">"</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    beta_min,</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    cost_min,</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#51da16"</span>,</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="vs">fr"Minimum </span><span class="kw">(</span><span class="dv">$\b</span><span class="vs">eta_1=</span><span class="sc">{</span>beta_min<span class="sc">:.3f}</span><span class="dv">$</span><span class="kw">)</span><span class="vs">"</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="vs">r"</span><span class="dv">$\b</span><span class="vs">eta_1</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Cost"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="vs">r"Lasso cost function for </span><span class="dv">$</span><span class="er">\</span><span class="vs">lambda = 0</span><span class="dv">.</span><span class="vs">1</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.gca()</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_locator(MultipleLocator(<span class="fl">0.5</span>))</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_minor_locator(MultipleLocator(<span class="fl">0.1</span>))</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_minor_locator(MultipleLocator(<span class="fl">0.1</span>))</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>ax.grid(which<span class="op">=</span><span class="st">"major"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>ax.grid(which<span class="op">=</span><span class="st">"minor"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>ax.axvline(</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">"--"</span></span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>plt.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="penalties_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="adf2ca9d" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">float</span>(<span class="bu">round</span>(<span class="bu">min</span>(cost), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>0.131</code></pre>
</div>
</div>
<p>The minimum of <span class="math inline">\(J\)</span> is <span class="math inline">\(0.131\)</span> and is reached at <span class="math inline">\(\beta_1=0.727\)</span>, so with a weak regularisation of <span class="math inline">\(\lambda=0.1\)</span> the Lasso will keep <span class="math inline">\(\beta_1\)</span> in the model.</p>
<p>Remember that <span class="math inline">\(\lambda_{lim}=2(\overline{xy} - \bar x\bar y)\)</span>, so let’s find it:</p>
<div id="5f013f74" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lambda_lim <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>(np.mean(x<span class="op">*</span>y) <span class="op">-</span> np.mean(x)<span class="op">*</span>np.mean(y))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">float</span>(<span class="bu">round</span>(lambda_lim, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>0.479</code></pre>
</div>
</div>
<p>It’s a bit higher than the value we’ve just tested, so as we increase <span class="math inline">\(\lambda\)</span> from <span class="math inline">\(0.1\)</span> to <span class="math inline">\(\lambda_{lim}\)</span>, we should see the minimum of <span class="math inline">\(J\)</span> slide leftward over to the orange point…</p>
<div id="e2287b31" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cost <span class="op">=</span> compute_cost(lambda_<span class="op">=</span>lambda_lim)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>min_idx <span class="op">=</span> np.argmin(cost)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>beta_min <span class="op">=</span> beta_1[min_idx]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>cost_min <span class="op">=</span> cost[min_idx]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>zero_idx <span class="op">=</span> np.argmin(np.<span class="bu">abs</span>(beta_1 <span class="op">-</span> <span class="dv">0</span>))</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>cost_zero <span class="op">=</span> cost[zero_idx]</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">5</span>))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>plt.plot(</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    beta_1,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    cost,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#721d98"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Cost function"</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    cost_zero,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#ff6d00"</span>,</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="vs">r"</span><span class="dv">$\b</span><span class="vs">eta_1 = 0</span><span class="dv">$</span><span class="vs">"</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    beta_min,</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    cost_min,</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#51da16"</span>,</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="vs">fr"Minimum </span><span class="kw">(</span><span class="dv">$\b</span><span class="vs">eta_1=</span><span class="sc">{</span>beta_min<span class="sc">:.3f}</span><span class="dv">$</span><span class="kw">)</span><span class="vs">"</span></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="vs">r"</span><span class="dv">$\b</span><span class="vs">eta_1</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Cost"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="vs">r"Lasso cost function for </span><span class="dv">$</span><span class="er">\</span><span class="vs">lambda = </span><span class="er">\</span><span class="vs">lambda_{lim}</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.gca()</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_locator(MultipleLocator(<span class="fl">0.5</span>))</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_minor_locator(MultipleLocator(<span class="fl">0.1</span>))</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_minor_locator(MultipleLocator(<span class="fl">0.1</span>))</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>ax.grid(which<span class="op">=</span><span class="st">"major"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>ax.grid(which<span class="op">=</span><span class="st">"minor"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>ax.axvline(</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">"--"</span></span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a>plt.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="penalties_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Bingo, we’ve just hit <span class="math inline">\(\beta_1=0\)</span>. Notice how as we increase <span class="math inline">\(\lambda\)</span>, an “elbow effect” starts to appear <span class="math inline">\(\beta_1=0\)</span>, that’s the effect of the higher weight we’re progressively putting on the absolute value in <span class="math inline">\(J\)</span>, which is basically making the absolute value “visually emerge” more in the graph.</p>
<p>Let’s see where the minimum of <span class="math inline">\(J\)</span> stands now:</p>
<div id="79da017b" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">float</span>(<span class="bu">round</span>(<span class="bu">min</span>(cost), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0.269</code></pre>
</div>
</div>
<p>With <span class="math inline">\(\lambda=\lambda_{lim}\)</span>, <span class="math inline">\(\beta_1\)</span> has been excluded from the model, but notice how the minimum of <span class="math inline">\(J\)</span> is now <span class="math inline">\(0.269\)</span>, higher than with <span class="math inline">\(\lambda=0.1\)</span> before? So, maybe the Lasso will tell itself that the ideal amount of regularisation ought not be so high… and that keeping <span class="math inline">\(\beta_1\)</span> in the model may be a good idea as it’ll better help explain the variation in <span class="math inline">\(y\)</span>.</p>
<p><em>Note</em>: we generated a series of <span class="math inline">\(\beta_1\)</span> with arbitrary resolution hence <span class="math inline">\(\hat\beta_1=0.002\)</span> and not a sharp <span class="math inline">\(0\)</span>, as <span class="math inline">\(0.002\)</span> happens to be the closest value we have to <span class="math inline">\(0\)</span> here. But, theoretically, the minimum is reached at <span class="math inline">\(\hat\beta_1=0\)</span> when <span class="math inline">\(\lambda=\lambda_{lim}\)</span>, and the feature is ruled out from the model. You’re free to rerun this script with a much finer grid of <span class="math inline">\(\beta_1\)</span> and observe how <span class="math inline">\(\hat\beta\)</span> approaches the exact <span class="math inline">\(0\)</span> the finer the grid is.</p>
<p>And from here on, if we keep increasing <span class="math inline">\(\lambda\)</span>, the minimum of the objective will stay <span class="math inline">\(\hat\beta_1=0\)</span> ! To illustrate that, let’s look at a <span class="math inline">\(\lambda=0.5\)</span> slightly over <span class="math inline">\(\lambda_{lim}\)</span>:</p>
<div id="ba5be4a6" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>cost <span class="op">=</span> compute_cost(lambda_<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>min_idx <span class="op">=</span> np.argmin(cost)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>beta_min <span class="op">=</span> beta_1[min_idx]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>cost_min <span class="op">=</span> cost[min_idx]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>zero_idx <span class="op">=</span> np.argmin(np.<span class="bu">abs</span>(beta_1 <span class="op">-</span> <span class="dv">0</span>))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>cost_zero <span class="op">=</span> cost[zero_idx]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">5</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>plt.plot(</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    beta_1,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    cost,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#721d98"</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"Cost function"</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    cost_zero,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#ff6d00"</span>,</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="vs">r"</span><span class="dv">$\b</span><span class="vs">eta_1 = 0</span><span class="dv">$</span><span class="vs">"</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>plt.scatter(</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>    beta_min,</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>    cost_min,</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"#51da16"</span>,</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="vs">fr"Minimum </span><span class="kw">(</span><span class="dv">$\b</span><span class="vs">eta_1=</span><span class="sc">{</span>beta_min<span class="sc">:.3f}</span><span class="dv">$</span><span class="kw">)</span><span class="vs">"</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="vs">r"</span><span class="dv">$\b</span><span class="vs">eta_1</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Cost"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="vs">r"Lasso cost function for </span><span class="dv">$</span><span class="er">\</span><span class="vs">lambda = 0</span><span class="dv">.</span><span class="vs">5</span><span class="dv">$</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.gca()</span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_locator(MultipleLocator(<span class="fl">0.5</span>))</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_minor_locator(MultipleLocator(<span class="fl">0.1</span>))</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_minor_locator(MultipleLocator(<span class="fl">0.1</span>))</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>ax.grid(which<span class="op">=</span><span class="st">"major"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>ax.grid(which<span class="op">=</span><span class="st">"minor"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, linestyle<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>ax.axvline(</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>,</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">"--"</span></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>plt.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="penalties_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="c8f1a0fd" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">float</span>(<span class="bu">round</span>(<span class="bu">min</span>(cost), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>0.269</code></pre>
</div>
</div>
<p>As expected, nothing changes. And same goes for <span class="math inline">\(\lambda=5,10,1000\dots\)</span></p>
<p>Before we round up, let’s generate a grid of 100 equally spaced lambdas between <span class="math inline">\(0\)</span> and <span class="math inline">\(\lambda_{lim}\)</span> and try to find for which of them Lasso and Ridge minimise their respective costs, and how those minimum costs compare. Before you look at the result do you expect some amount of regularisation to help lower the smallest possible cost of our simple <span class="math inline">\(f\)</span> model?</p>
<div id="f0a66906" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lambdas <span class="op">=</span> np.linspace(<span class="dv">0</span>, lambda_lim, <span class="dv">100</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>costs_lasso <span class="op">=</span> [<span class="bu">min</span>([np.mean(np.square(y<span class="op">-</span>beta_0[i]<span class="op">-</span>beta_1[i]<span class="op">*</span>x)) <span class="op">+</span> lam<span class="op">*</span><span class="bu">abs</span>(beta_1[i]) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(res)]) <span class="cf">for</span> lam <span class="kw">in</span> lambdas]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>costs_ridge <span class="op">=</span> [<span class="bu">min</span>([np.mean(np.square(y<span class="op">-</span>beta_0[i]<span class="op">-</span>beta_1[i]<span class="op">*</span>x)) <span class="op">+</span> lam<span class="op">*</span>(beta_1[i])<span class="op">**</span><span class="dv">2</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(res)]) <span class="cf">for</span> lam <span class="kw">in</span> lambdas]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Lasso smallest cost: '</span>, <span class="bu">round</span>(<span class="bu">min</span>(costs_lasso), <span class="dv">3</span>), <span class="st">', reached with lambda ='</span>, lambdas[np.argmin(costs_lasso)])</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Ridge smallest cost: '</span>, <span class="bu">round</span>(<span class="bu">min</span>(costs_ridge), <span class="dv">3</span>), <span class="st">', reached with lambda ='</span>, lambdas[np.argmin(costs_ridge)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lasso smallest cost:  0.049 , reached with lambda = 0.0
Ridge smallest cost:  0.049 , reached with lambda = 0.0</code></pre>
</div>
</div>
<p>Does this result surprise you? Did you expect something else? Turns out zero regularisation yields the lowest cost with both Lasso and Ridge. One could say this is because the very problem mentioned by Hastie &amp; Tibshirani in the interlude does not exist here, since we’re working with only one feature (<span class="math inline">\(x\)</span>), so any regularisation does more harm than good in this excruciatingly simple dataset with zero collinearity. Anyway, our goal here was just to understand how those two regularisation methods work, and our simple model does the job even though regularisation is of no use here.</p>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>Thanks to those nice visualisations, we were able to understand what happens to the shape of the Lasso cost function as we vary the regularisation strength <span class="math inline">\(\lambda\)</span>. The more <span class="math inline">\(\lambda\)</span> goes up, the less smooth the cost curve looks, and an “elbow effect” starts showing up at <span class="math inline">\(\beta_1=0\)</span> which eventually ends up becoming the global minimum of the cost once <span class="math inline">\(\lambda\)</span> reached <span class="math inline">\(\lambda_{lim}\)</span> and beyond. That is how some coefficients end up (contrary to Ridge) actually zero’ed out with enough regularisation, and that’s what the Lasso algorithm decides to do when there’s serious collinearity in your dataset.</p>
<p>You’re now ready to show those employees that not enough red bull always had the potential to end their career.</p>
<center>
<img src="end-career-supa.png" alt="drawing" width="400">
</center>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>